---
- name: nxos_facts module
  hosts: nxos
  vars:
    nxapi:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: nxapi
      use_ssl: yes
      validate_certs: no
      port: 8443

    vlans:
      - vlan_id: 100
        admin_state: up
        name: IT
      - vlan_id: 200
        admin_state: up
        name: SALES
      - vlan_id: 300
        admin_state: up
        name: HR
        
  tasks:
    - name: nxos_facts nxapi
      nxos_facts:
        provider: "{{ nxapi }}"
    - name: Configure Nexus VLANs
      nxos_vlan:
        provider: "{{ nxapi }}"
        vlan_id: "{{ item.vlan_id }}"
        admin_state: "{{ item.admin_state }}"
        name: "{{ item.name }}"
      with_items: "{{ vlans }}"